<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>TimecodeBridge</AssemblyName>
    <RootNamespace>TimecodeBridge</RootNamespace>
    <Version>1.0.1</Version>
    <Product>Timecode Bridge</Product>
    <Description>SMPTE LTC (audio) to Art-Net timecode bridge</Description>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <InvariantGlobalization>true</InvariantGlobalization>
    <TieredPgo>true</TieredPgo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

</Project>
